### PR TITLE
Add atk dependencies to support accessibility.

### PR DESCRIPTION
**Pull request by wanchao-xu**

### CODE REVIEW

**Comment by swift-kim** [comment]
Are these libraries generally available for all profiles? I can't see `libatk*.so` from the wearable 4.0 rootstrap.

**Comment by wanchao-xu** [comment]
> Are these libraries generally available for all profiles? I can't see `libatk*.so` from the wearable 4.0 rootstrap.

The atk library is downloaded from http://download.tizen.org/snapshots/tizen/5.5-unified/latest/repos/standard/packages/

**Comment by swift-kim** [comment]
@wanchao-xu If the library is not present in the rootstrap, it generally means that the embedder cannot run on watch devices or at least the app cannot be uploaded to the watch app store because it's using non-public API. You need to check on which devices (mobile, wearable, tv, common) the libraries are available.

**Comment by wanchao-xu** [comment]
@swift-kim , I checked the library on device, the TV, mobile and wearable support atk library, and RB5 doens't support accessibility, so common doesn't have atk libraty.

**Comment by swift-kim** [comment]
I can find atk-related libraries on my RPi4 device. Maybe the accessibility support has just not been added to RB5 devices yet.

```sh
bash-3.2# find /lib64/ -name *atk*
/lib64/libatk-1.0.so.0
/lib64/libatk-bridge-2.0.so.0.0.0
/lib64/libatk-1.0.so.0.23609.1
/lib64/libatk-bridge-2.0.so.0
```

We still need to check if any non-public API is being used in the engine or embedder. Let's continue the discussion in the engine side PR.

**Review by swift-kim — APPROVED** [review]

**Pull request merged**
