### PR TITLE
Change rpm package version 5.5 to 6.5 for NUI

### PR DESCRIPTION
**Pull request by JSUYA**
NUI is supported from Tizen 6.5. So change the version of rpm.
It also adds the dali package for NUI support.

### CODE REVIEW

**Comment by JSUYA** [comment]
I haven't been able to find the issues that might be caused by this change yet.

I've made this PR for reference for progress of https://github.com/flutter-tizen/flutter-tizen/issues/351 .
I will reopen when ready for review.

**Comment by JSUYA** [comment]
What I've checked is that we need to add the no warning flag to flutter/third_part/accessibility/ax.
```diff
diff --git a/third_party/accessibility/ax/BUILD.gn b/third_party/accessibility/ax/BUILD.gn
index 742dffd03c..c5ec63e66e 100644
--- a/third_party/accessibility/ax/BUILD.gn
+++ b/third_party/accessibility/ax/BUILD.gn
@@ -119,6 +122,16 @@ source_set("ax") {
       "glib-2.0",
       "gobject-2.0",
     ]
+
+    cflags = [
+      "-Wno-deprecated-declarations",
+      "-Wno-c++11-narrowing",
+    ]
+
+    cflags_cc = [
+      "-Wno-deprecated-declarations",
+      "-Wno-c++11-narrowing",
+    ]
   }
 
   public_deps = [

```

And the engine(x86) is not built in the llvm + ubuntu 18.04 environment. (use tizen toolchain)
(binutils pacakge version should be 2.33 or higher. ubuntu 18.04 is 2.30 https://packages.ubuntu.com/bionic/devel/binutils)

**Comment by bbrto21** [comment]
> I haven't been able to find all the issues that might be caused by this change yet.

Could you please consider this [problem](https://github.com/flutter-tizen/flutter-tizen/issues/351#issuecomment-1183064479)?

**Comment by swift-kim** [comment]
The Tizen Studio toolchain has been [deprecated](https://github.com/flutter-tizen/tizen_tools#using-tizen-studios-built-in-toolchain-deprecated). You should not use it.

**Comment by JSUYA** [comment]
> The Tizen Studio toolchain has been [deprecated](https://github.com/flutter-tizen/tizen_tools#using-tizen-studios-built-in-toolchain-deprecated). You should not use it.

I know it's deprecated. I couldn't find a way to solve the problem with the version of binutils in the llvm + ubuntu 18.04 environment (with tizen 6.5 rpms).
I think we can undo deprecated and use tizen toolchain in this cases.
(I think we can provide additional guidance on menual for ubuntu 18.04 users to use tizen toolchain.)
what do you think?

**Comment by JSUYA** [comment]
> > I haven't been able to find all the issues that might be caused by this change yet.
> 
> Could you please consider this [problem](https://github.com/flutter-tizen/flutter-tizen/issues/351#issuecomment-1183064479)?

I think branch out is necessary.
we can branch out to a supported version and announce this (like [TizenFX](https://github.com/Samsung/TizenFX#branches))

ex)
Supported devices
 - galaxy watch : Tizen 4.0 (flutter-3.0.0-tizen)
 - Smart TV : Tizen 6.0(flutter-3.0.0-tizen) / later(flutter-3.0.5-tizen higher)
 - blah blah
 
Without doing so...  Is there any way in the future that the flutter-tizen project can always support the latest version of tizen?
Please share any ideas we can do to complete the NUIFlutterView.

**Comment by swift-kim** [comment]
How do other platforms handle such situation?

How about using [dlopen()](https://stackoverflow.com/questions/1067346/alternatives-to-dlsym-and-dlopen-in-c) with a wrapper library that has an empty implementation?

**Comment by JSUYA** [comment]
https://github.com/flutter-tizen/tizen_tools/pull/27

**Pull request closed without merging**
